/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.controldepersonal.interfazClienteServicios;

import org.controldepersonal.conector.conector;

/**
 *
 * @author Miguel
 */
public class BuscaServicioPuestoNuevo extends javax.swing.JDialog {

    /**
     * Creates new form BuscaServicioPuestoNuevo
     */
    conector conexionactual;
    public BuscaServicioPuestoNuevo(java.awt.Frame parent, boolean modal,conector conexionactual) {
        super(parent, modal);
        this.conexionactual = conexionactual;
        initComponents();
        setTitle("Nuevo Puesto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spPuestoNuevo = new javax.swing.JScrollPane();
        pNuevoPuesto = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        lblPuestoNuevoDescripcion = new javax.swing.JLabel();
        txtPuestoNuevoDescripcion = new javax.swing.JTextField();
        lblPuestoNuevoTipo = new javax.swing.JLabel();
        txtPuestoNuevoTipo = new javax.swing.JTextField();
        lblPuestoNuevoHorario = new javax.swing.JLabel();
        lblPuestoNuevoVacante = new javax.swing.JLabel();
        txtPuestoNuevoVacante = new javax.swing.JTextField();
        txtPuestoNuevoTipoHorario = new javax.swing.JTextField();
        lblPuestoNuevoLaboral = new javax.swing.JLabel();
        cbPuestoNuevoLunes = new javax.swing.JCheckBox();
        cbPuestoNuevoMartes = new javax.swing.JCheckBox();
        cbPuestoNuevoMiercoles = new javax.swing.JCheckBox();
        cbPuestoNuevoJueves = new javax.swing.JCheckBox();
        cbPuestoNuevo = new javax.swing.JCheckBox();
        cbPuestoNuevoSabado = new javax.swing.JCheckBox();
        cbPuestoNuevoDomingo = new javax.swing.JCheckBox();
        lblPuestoNuevoHorarioLaboral = new javax.swing.JLabel();
        lblPuestoNuevoEntrada = new javax.swing.JLabel();
        txtPuestoNuevoHoraInicioLunes = new javax.swing.JTextField();
        txtPuestoNuevoHoraInicioMartes = new javax.swing.JTextField();
        txtPuestoNuevoHoraInicioMiercoles = new javax.swing.JTextField();
        txtPuestoNuevoHoraInicioJueves = new javax.swing.JTextField();
        txtPuestoNuevoHoraInicioViernes = new javax.swing.JTextField();
        txtPuestoNuevoHoraInicioSabado = new javax.swing.JTextField();
        txtPuestoNuevoHoraInicioDomingo = new javax.swing.JTextField();
        lblPuestoNuevoSalida = new javax.swing.JLabel();
        txtPuestoNuevoSalidaLunes = new javax.swing.JTextField();
        txtPuestoNuevoSalidaMartes = new javax.swing.JTextField();
        txtPuestoNuevoSalidaMiercoles = new javax.swing.JTextField();
        txtPuestoNuevoSalidaJueves = new javax.swing.JTextField();
        txtPuestoNuevoSalidaViernes = new javax.swing.JTextField();
        txtPuestoNuevoSalidaSabado = new javax.swing.JTextField();
        txtPuestoNuevoSalidaDomingo = new javax.swing.JTextField();
        btnPuestoNuevoRegistrar = new javax.swing.JButton();
        lblPuestoNuevoInicio = new javax.swing.JLabel();
        dpPuestoNuevoInicio = new org.jdesktop.swingx.JXDatePicker();
        lblPuestoNuevoFin = new javax.swing.JLabel();
        dpPuestoNuevoFin = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblPuestoNuevoDescripcion.setText("Descripción:");

        lblPuestoNuevoTipo.setText("Tipo:");

        lblPuestoNuevoHorario.setText("Tipo de Horario:");

        lblPuestoNuevoVacante.setText("Elementos para cubrir la vacante:");

        lblPuestoNuevoLaboral.setText("Días laborales:");

        cbPuestoNuevoLunes.setText("Lunes");

        cbPuestoNuevoMartes.setText("Martes");

        cbPuestoNuevoMiercoles.setText("Miercoles");

        cbPuestoNuevoJueves.setText("Jueves");

        cbPuestoNuevo.setText("Viernes");

        cbPuestoNuevoSabado.setText("Sábado");

        cbPuestoNuevoDomingo.setText("Domingo");

        lblPuestoNuevoHorarioLaboral.setText("Horario laboral:");

        lblPuestoNuevoEntrada.setText("Entrada:");

        lblPuestoNuevoSalida.setText("Salida:");

        btnPuestoNuevoRegistrar.setText("Registrar");

        lblPuestoNuevoInicio.setText("Inicio:");

        lblPuestoNuevoFin.setText("Fin:");

        javax.swing.GroupLayout pNuevoPuestoLayout = new javax.swing.GroupLayout(pNuevoPuesto);
        pNuevoPuesto.setLayout(pNuevoPuestoLayout);
        pNuevoPuestoLayout.setHorizontalGroup(
            pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                        .addComponent(btnPuestoNuevoRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                            .addComponent(lblPuestoNuevoLaboral)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblPuestoNuevoHorarioLaboral)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblPuestoNuevoEntrada)
                            .addGap(72, 72, 72)
                            .addComponent(lblPuestoNuevoSalida))
                        .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                            .addComponent(lblPuestoNuevoDescripcion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPuestoNuevoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                            .addComponent(lblPuestoNuevoTipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPuestoNuevoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                            .addComponent(lblPuestoNuevoHorario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPuestoNuevoTipoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                            .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                                    .addComponent(lblPuestoNuevoVacante)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPuestoNuevoVacante, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                                    .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbPuestoNuevoLunes)
                                        .addComponent(cbPuestoNuevoMartes)
                                        .addComponent(cbPuestoNuevoMiercoles)
                                        .addComponent(cbPuestoNuevoJueves)
                                        .addComponent(cbPuestoNuevo)
                                        .addComponent(cbPuestoNuevoSabado)
                                        .addComponent(cbPuestoNuevoDomingo))
                                    .addGap(66, 66, 66)
                                    .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPuestoNuevoHoraInicioLunes)
                                        .addComponent(txtPuestoNuevoHoraInicioMartes)
                                        .addComponent(txtPuestoNuevoHoraInicioMiercoles)
                                        .addComponent(txtPuestoNuevoHoraInicioJueves)
                                        .addComponent(txtPuestoNuevoHoraInicioViernes)
                                        .addComponent(txtPuestoNuevoHoraInicioSabado)
                                        .addComponent(txtPuestoNuevoHoraInicioDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(46, 46, 46)
                            .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPuestoNuevoSalidaLunes)
                                .addComponent(txtPuestoNuevoSalidaMartes)
                                .addComponent(txtPuestoNuevoSalidaMiercoles)
                                .addComponent(txtPuestoNuevoSalidaJueves)
                                .addComponent(txtPuestoNuevoSalidaViernes)
                                .addComponent(txtPuestoNuevoSalidaSabado)
                                .addComponent(txtPuestoNuevoSalidaDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                            .addComponent(lblPuestoNuevoInicio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dpPuestoNuevoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(lblPuestoNuevoFin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dpPuestoNuevoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        pNuevoPuestoLayout.setVerticalGroup(
            pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNuevoPuestoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuestoNuevoDescripcion)
                    .addComponent(txtPuestoNuevoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuestoNuevoTipo)
                    .addComponent(txtPuestoNuevoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuestoNuevoHorario)
                    .addComponent(txtPuestoNuevoTipoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpPuestoNuevoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuestoNuevoInicio)
                    .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dpPuestoNuevoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPuestoNuevoFin)))
                .addGap(9, 9, 9)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuestoNuevoVacante)
                    .addComponent(txtPuestoNuevoVacante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuestoNuevoLaboral)
                    .addComponent(lblPuestoNuevoHorarioLaboral)
                    .addComponent(lblPuestoNuevoEntrada)
                    .addComponent(lblPuestoNuevoSalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPuestoNuevoLunes)
                    .addComponent(txtPuestoNuevoHoraInicioLunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuestoNuevoSalidaLunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPuestoNuevoMartes)
                    .addComponent(txtPuestoNuevoHoraInicioMartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuestoNuevoSalidaMartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPuestoNuevoMiercoles)
                    .addComponent(txtPuestoNuevoHoraInicioMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuestoNuevoSalidaMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPuestoNuevoJueves)
                    .addComponent(txtPuestoNuevoHoraInicioJueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuestoNuevoSalidaJueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPuestoNuevo)
                    .addComponent(txtPuestoNuevoHoraInicioViernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuestoNuevoSalidaViernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPuestoNuevoSabado)
                    .addComponent(txtPuestoNuevoHoraInicioSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuestoNuevoSalidaSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPuestoNuevoDomingo)
                    .addComponent(txtPuestoNuevoHoraInicioDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuestoNuevoSalidaDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pNuevoPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnPuestoNuevoRegistrar))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        spPuestoNuevo.setViewportView(pNuevoPuesto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spPuestoNuevo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spPuestoNuevo)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPuestoNuevoRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox cbPuestoNuevo;
    private javax.swing.JCheckBox cbPuestoNuevoDomingo;
    private javax.swing.JCheckBox cbPuestoNuevoJueves;
    private javax.swing.JCheckBox cbPuestoNuevoLunes;
    private javax.swing.JCheckBox cbPuestoNuevoMartes;
    private javax.swing.JCheckBox cbPuestoNuevoMiercoles;
    private javax.swing.JCheckBox cbPuestoNuevoSabado;
    private org.jdesktop.swingx.JXDatePicker dpPuestoNuevoFin;
    private org.jdesktop.swingx.JXDatePicker dpPuestoNuevoInicio;
    private javax.swing.JLabel lblPuestoNuevoDescripcion;
    private javax.swing.JLabel lblPuestoNuevoEntrada;
    private javax.swing.JLabel lblPuestoNuevoFin;
    private javax.swing.JLabel lblPuestoNuevoHorario;
    private javax.swing.JLabel lblPuestoNuevoHorarioLaboral;
    private javax.swing.JLabel lblPuestoNuevoInicio;
    private javax.swing.JLabel lblPuestoNuevoLaboral;
    private javax.swing.JLabel lblPuestoNuevoSalida;
    private javax.swing.JLabel lblPuestoNuevoTipo;
    private javax.swing.JLabel lblPuestoNuevoVacante;
    private javax.swing.JPanel pNuevoPuesto;
    private javax.swing.JScrollPane spPuestoNuevo;
    private javax.swing.JTextField txtPuestoNuevoDescripcion;
    private javax.swing.JTextField txtPuestoNuevoHoraInicioDomingo;
    private javax.swing.JTextField txtPuestoNuevoHoraInicioJueves;
    private javax.swing.JTextField txtPuestoNuevoHoraInicioLunes;
    private javax.swing.JTextField txtPuestoNuevoHoraInicioMartes;
    private javax.swing.JTextField txtPuestoNuevoHoraInicioMiercoles;
    private javax.swing.JTextField txtPuestoNuevoHoraInicioSabado;
    private javax.swing.JTextField txtPuestoNuevoHoraInicioViernes;
    private javax.swing.JTextField txtPuestoNuevoSalidaDomingo;
    private javax.swing.JTextField txtPuestoNuevoSalidaJueves;
    private javax.swing.JTextField txtPuestoNuevoSalidaLunes;
    private javax.swing.JTextField txtPuestoNuevoSalidaMartes;
    private javax.swing.JTextField txtPuestoNuevoSalidaMiercoles;
    private javax.swing.JTextField txtPuestoNuevoSalidaSabado;
    private javax.swing.JTextField txtPuestoNuevoSalidaViernes;
    private javax.swing.JTextField txtPuestoNuevoTipo;
    private javax.swing.JTextField txtPuestoNuevoTipoHorario;
    private javax.swing.JTextField txtPuestoNuevoVacante;
    // End of variables declaration//GEN-END:variables
}
