/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.controldepersonal.interfazClienteServicios;

import org.controldepersonal.conector.conector;

/**
 *
 * @author Miguel
 */
public class BuscaCliente extends javax.swing.JDialog {

    /**
     * Creates new form BuscaCliente
     */
    conector conexionactual;
    public BuscaCliente(java.awt.Frame parent, boolean modal,conector conexionactual,String nombreCliente) {
        super(parent, modal);
        this.conexionactual = conexionactual;
        initComponents();
        setTitle("Busqueda de Cliente");
        txtNombreClienteBusca.setText(nombreCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spBuscaCliente = new javax.swing.JScrollPane();
        pBuscaCliente = new javax.swing.JPanel();
        lblClienteNombreBusca = new javax.swing.JLabel();
        txtNombreClienteBusca = new javax.swing.JTextField();
        lblGiroBusca = new javax.swing.JLabel();
        txtGiroBusca = new javax.swing.JTextField();
        txtRFCBusca = new javax.swing.JTextField();
        lblRFCBusca = new javax.swing.JLabel();
        txtNombreComercialBusca = new javax.swing.JTextField();
        lblNombreComercialBusca = new javax.swing.JLabel();
        lblRazonSocialBusca = new javax.swing.JLabel();
        txtRazonSocialBusca = new javax.swing.JTextField();
        tpDatosClienteBusca = new javax.swing.JTabbedPane();
        pGeneralesBusca = new javax.swing.JPanel();
        lblDomicilio2 = new javax.swing.JLabel();
        txtDomicilio2 = new javax.swing.JTextField();
        lblExterior2 = new javax.swing.JLabel();
        txtNumeroExterior2 = new javax.swing.JTextField();
        lblInterior2 = new javax.swing.JLabel();
        txtNumeroInterior2 = new javax.swing.JTextField();
        lblColonia2 = new javax.swing.JLabel();
        txtColonia2 = new javax.swing.JTextField();
        lblCodPostal2 = new javax.swing.JLabel();
        txtCodPostal2 = new javax.swing.JTextField();
        cbAltaCIESP2 = new javax.swing.JCheckBox();
        lblHorario2 = new javax.swing.JLabel();
        txtHorario2 = new javax.swing.JTextField();
        lblEstado2 = new javax.swing.JLabel();
        cbEstados2 = new javax.swing.JComboBox();
        lblMunicipio2 = new javax.swing.JLabel();
        cbMunicipios2 = new javax.swing.JComboBox();
        lblTelefonos2 = new javax.swing.JLabel();
        txtTelefonos2 = new javax.swing.JTextField();
        lblRepresentante2 = new javax.swing.JLabel();
        txtRepresentante2 = new javax.swing.JTextField();
        lblRepTelOficina2 = new javax.swing.JLabel();
        txtRepTelOficina2 = new javax.swing.JTextField();
        lblRepTelCelular2 = new javax.swing.JLabel();
        txtRepTelCelular2 = new javax.swing.JTextField();
        lblRepCorreo2 = new javax.swing.JLabel();
        txtRepCorreo2 = new javax.swing.JTextField();
        lblEncargado2 = new javax.swing.JLabel();
        txtEncargado2 = new javax.swing.JTextField();
        lblEncTelOficina2 = new javax.swing.JLabel();
        txtEncTelOficina2 = new javax.swing.JTextField();
        lblEncTelCelular2 = new javax.swing.JLabel();
        txtEncTelCelular2 = new javax.swing.JTextField();
        lblEncCorreo2 = new javax.swing.JLabel();
        txtEncCorreo2 = new javax.swing.JTextField();
        lblServiciosInicio2 = new javax.swing.JLabel();
        dpInicioServicios2 = new org.jdesktop.swingx.JXDatePicker();
        lblVigenciaContrato2 = new javax.swing.JLabel();
        dpVigenciaServicios2 = new org.jdesktop.swingx.JXDatePicker();
        lblComentarios2 = new javax.swing.JLabel();
        txtComentarios2 = new javax.swing.JTextField();
        pPagos = new javax.swing.JPanel();
        lblPagos = new javax.swing.JLabel();
        txtPagos = new javax.swing.JTextField();
        lblPagosTelOficina = new javax.swing.JLabel();
        txtPagosTelOficina = new javax.swing.JTextField();
        lblPagosCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblFacturación = new javax.swing.JLabel();
        rbMensual = new javax.swing.JRadioButton();
        rbQuincenal = new javax.swing.JRadioButton();
        rbEvento = new javax.swing.JRadioButton();
        lblRevision = new javax.swing.JLabel();
        txtRevision = new javax.swing.JTextField();
        lblDiaPagos = new javax.swing.JLabel();
        txtDiaPagos = new javax.swing.JTextField();
        pTotalFacturacion = new javax.swing.JPanel();
        lblSubtotal = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtFacturaSubtotal = new javax.swing.JTextField();
        txtFacturaIVA = new javax.swing.JTextField();
        txtFacturaTotal = new javax.swing.JTextField();
        lblPesos1 = new javax.swing.JLabel();
        lblPesos2 = new javax.swing.JLabel();
        lblPesos3 = new javax.swing.JLabel();
        pServicios = new javax.swing.JPanel();
        spServicios = new javax.swing.JScrollPane();
        tServicios = new javax.swing.JTable();
        btnDetalles = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevoServicio = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblClienteNombreBusca.setText("Cliente:");

        txtNombreClienteBusca.setEnabled(false);

        lblGiroBusca.setText("Giro:");

        txtGiroBusca.setEnabled(false);

        txtRFCBusca.setEnabled(false);

        lblRFCBusca.setText("RFC:");

        txtNombreComercialBusca.setEnabled(false);

        lblNombreComercialBusca.setText("Nombre Comercial:");

        lblRazonSocialBusca.setText("Razón Social:");

        txtRazonSocialBusca.setEnabled(false);

        lblDomicilio2.setText("Domicilio:");

        txtDomicilio2.setEnabled(false);

        lblExterior2.setText("No. Exterior:");

        txtNumeroExterior2.setEnabled(false);

        lblInterior2.setText("No. Interior:");

        txtNumeroInterior2.setEnabled(false);

        lblColonia2.setText("Colonia:");

        txtColonia2.setEnabled(false);

        lblCodPostal2.setText("Código Postal:");

        txtCodPostal2.setEnabled(false);

        cbAltaCIESP2.setText("Alta CIESP");

        lblHorario2.setText("Horario:");

        txtHorario2.setEnabled(false);

        lblEstado2.setText("Estado:");

        cbEstados2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige un estado" }));

        lblMunicipio2.setText("Municipio:");

        cbMunicipios2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige un municipio" }));

        lblTelefonos2.setText("Teléfonos:");

        txtTelefonos2.setEnabled(false);

        lblRepresentante2.setText("Representante legal:");

        txtRepresentante2.setEnabled(false);

        lblRepTelOficina2.setText("Teléfono de Oficina:");

        txtRepTelOficina2.setEnabled(false);

        lblRepTelCelular2.setText("Celular:");

        txtRepTelCelular2.setEnabled(false);

        lblRepCorreo2.setText("Correo:");

        txtRepCorreo2.setEnabled(false);

        lblEncargado2.setText("Encargado de seguridad:");

        txtEncargado2.setEnabled(false);

        lblEncTelOficina2.setText("Teléfono de Oficina:");

        txtEncTelOficina2.setEnabled(false);

        lblEncTelCelular2.setText("Celular");

        txtEncTelCelular2.setEnabled(false);

        lblEncCorreo2.setText("Correo:");

        txtEncCorreo2.setEnabled(false);

        lblServiciosInicio2.setText("Inicio de servicios:");

        lblVigenciaContrato2.setText("Vigencia de contrato:");

        lblComentarios2.setText("Comentarios:");

        txtComentarios2.setEnabled(false);

        javax.swing.GroupLayout pGeneralesBuscaLayout = new javax.swing.GroupLayout(pGeneralesBusca);
        pGeneralesBusca.setLayout(pGeneralesBuscaLayout);
        pGeneralesBuscaLayout.setHorizontalGroup(
            pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                        .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDomicilio2)
                                    .addComponent(lblColonia2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtColonia2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtDomicilio2)))
                            .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                                .addComponent(lblEstado2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbEstados2, 0, 201, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                                        .addComponent(lblExterior2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumeroExterior2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblInterior2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumeroInterior2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                                        .addComponent(lblCodPostal2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodPostal2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                                        .addComponent(lblHorario2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbAltaCIESP2)))
                            .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                                .addComponent(lblMunicipio2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMunicipios2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                        .addComponent(lblTelefonos2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefonos2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                        .addComponent(lblRepresentante2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRepresentante2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRepTelOficina2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRepTelOficina2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRepTelCelular2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRepTelCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                        .addComponent(lblRepCorreo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRepCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                        .addComponent(lblEncTelCelular2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEncTelCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEncCorreo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEncCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                        .addComponent(lblServiciosInicio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpInicioServicios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVigenciaContrato2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpVigenciaServicios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pGeneralesBuscaLayout.createSequentialGroup()
                            .addComponent(lblComentarios2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtComentarios2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pGeneralesBuscaLayout.createSequentialGroup()
                            .addComponent(lblEncargado2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEncargado2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblEncTelOficina2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEncTelOficina2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        pGeneralesBuscaLayout.setVerticalGroup(
            pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGeneralesBuscaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDomicilio2)
                    .addComponent(txtDomicilio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExterior2)
                    .addComponent(txtNumeroExterior2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInterior2)
                    .addComponent(txtNumeroInterior2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAltaCIESP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColonia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColonia2)
                    .addComponent(lblCodPostal2)
                    .addComponent(txtCodPostal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorario2)
                    .addComponent(txtHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado2)
                    .addComponent(lblMunicipio2)
                    .addComponent(cbMunicipios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRepresentante2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRepresentante2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRepTelOficina2)
                        .addComponent(txtRepTelOficina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRepTelCelular2)
                        .addComponent(txtRepTelCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRepCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRepCorreo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEncargado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEncargado2)
                    .addComponent(lblEncTelOficina2)
                    .addComponent(txtEncTelOficina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEncTelCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEncTelCelular2)
                    .addComponent(lblEncCorreo2)
                    .addComponent(txtEncCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpInicioServicios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiciosInicio2)
                    .addComponent(lblVigenciaContrato2)
                    .addComponent(dpVigenciaServicios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGeneralesBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComentarios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComentarios2))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        tpDatosClienteBusca.addTab("Datos generales", pGeneralesBusca);

        lblPagos.setText("Encargado de pagar:");

        txtPagos.setEnabled(false);

        lblPagosTelOficina.setText("Teléfono de Oficina:");

        txtPagosTelOficina.setEnabled(false);

        lblPagosCelular.setText("Celular");

        txtCelular.setEnabled(false);

        lblCorreo.setText("Correo:");

        txtCorreo.setEnabled(false);

        lblFacturación.setText("Facturación:");

        rbMensual.setText("Mensual");

        rbQuincenal.setText("Quicenal");

        rbEvento.setText("Por evento");

        lblRevision.setText("Revisión:");

        txtRevision.setEnabled(false);

        lblDiaPagos.setText("Pagos:");

        txtDiaPagos.setEnabled(false);

        lblSubtotal.setText("Factura subtotal:");

        lblIVA.setText("IVA:");

        lblTotal.setText("Total:");

        txtFacturaSubtotal.setEnabled(false);

        txtFacturaIVA.setEnabled(false);

        txtFacturaTotal.setEnabled(false);

        lblPesos1.setText("pesos");

        lblPesos2.setText("pesos");

        lblPesos3.setText("pesos");

        javax.swing.GroupLayout pTotalFacturacionLayout = new javax.swing.GroupLayout(pTotalFacturacion);
        pTotalFacturacion.setLayout(pTotalFacturacionLayout);
        pTotalFacturacionLayout.setHorizontalGroup(
            pTotalFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTotalFacturacionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pTotalFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTotal)
                    .addComponent(lblIVA)
                    .addComponent(lblSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTotalFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFacturaSubtotal)
                    .addComponent(txtFacturaIVA)
                    .addComponent(txtFacturaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTotalFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPesos1)
                    .addComponent(lblPesos2)
                    .addComponent(lblPesos3))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        pTotalFacturacionLayout.setVerticalGroup(
            pTotalFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTotalFacturacionLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pTotalFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(txtFacturaSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTotalFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIVA)
                    .addComponent(txtFacturaIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTotalFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtFacturaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesos3))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pPagosLayout = new javax.swing.GroupLayout(pPagos);
        pPagos.setLayout(pPagosLayout);
        pPagosLayout.setHorizontalGroup(
            pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPagosLayout.createSequentialGroup()
                        .addComponent(lblPagos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPagosLayout.createSequentialGroup()
                        .addComponent(lblCorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPagosLayout.createSequentialGroup()
                            .addComponent(lblFacturación)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbMensual)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbQuincenal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbEvento))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPagosLayout.createSequentialGroup()
                            .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRevision)
                                .addComponent(lblDiaPagos))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDiaPagos)
                                .addComponent(txtRevision)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPagosLayout.createSequentialGroup()
                        .addComponent(lblPagosTelOficina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPagosTelOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPagosCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPagosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pTotalFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        pPagosLayout.setVerticalGroup(
            pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPagosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagos)
                    .addComponent(txtPagosTelOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagosTelOficina)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagosCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPagosLayout.createSequentialGroup()
                        .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCorreo))
                        .addGap(45, 45, 45)
                        .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMensual)
                            .addComponent(rbQuincenal)
                            .addComponent(rbEvento)
                            .addComponent(lblFacturación))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRevision))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaPagos)))
                    .addComponent(pTotalFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        tpDatosClienteBusca.addTab("Pagos", pPagos);

        tServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"vre vr ve r", "mvmrovrn", "34", "33"},
                {"vnrinervei", "vmreivnier", "44", "33"}
            },
            new String [] {
                "Servicio", "Inicio de Servicio", "Elementos requeridos", "Elementos registrados"
            }
        ));
        spServicios.setViewportView(tServicios);

        btnDetalles.setText("Detalles");

        javax.swing.GroupLayout pServiciosLayout = new javax.swing.GroupLayout(pServicios);
        pServicios.setLayout(pServiciosLayout);
        pServiciosLayout.setHorizontalGroup(
            pServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spServicios, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pServiciosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(355, 355, 355))
        );
        pServiciosLayout.setVerticalGroup(
            pServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalles)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tpDatosClienteBusca.addTab("Servicios", pServicios);

        btnRegistrar.setText("Registrar");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevoServicio.setText("Nuevo Servicio");
        btnNuevoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoServicioActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar Servicios");

        btnModificar.setText("Actualizar datos");

        javax.swing.GroupLayout pBuscaClienteLayout = new javax.swing.GroupLayout(pBuscaCliente);
        pBuscaCliente.setLayout(pBuscaClienteLayout);
        pBuscaClienteLayout.setHorizontalGroup(
            pBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBuscaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpDatosClienteBusca)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBuscaClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevoServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pBuscaClienteLayout.createSequentialGroup()
                        .addGroup(pBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreComercialBusca)
                            .addComponent(lblClienteNombreBusca)
                            .addComponent(lblRazonSocialBusca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreComercialBusca)
                            .addComponent(txtNombreClienteBusca)
                            .addComponent(txtRazonSocialBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pBuscaClienteLayout.createSequentialGroup()
                                .addComponent(lblGiroBusca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiroBusca))
                            .addGroup(pBuscaClienteLayout.createSequentialGroup()
                                .addComponent(lblRFCBusca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRFCBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pBuscaClienteLayout.setVerticalGroup(
            pBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBuscaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteNombreBusca)
                    .addComponent(txtNombreClienteBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiroBusca)
                    .addComponent(txtGiroBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreComercialBusca)
                    .addComponent(txtNombreComercialBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRFCBusca)
                    .addComponent(txtRFCBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazonSocialBusca)
                    .addComponent(txtRazonSocialBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tpDatosClienteBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnRegistrar)
                    .addComponent(btnNuevoServicio)
                    .addComponent(btnActualizar)
                    .addComponent(btnModificar))
                .addContainerGap())
        );

        spBuscaCliente.setViewportView(pBuscaCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spBuscaCliente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spBuscaCliente)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoServicioActionPerformed
        NuevoServicio nuevo = new NuevoServicio(new javax.swing.JFrame(), false, conexionactual,txtNombreClienteBusca.getText().toUpperCase());
        nuevo.setVisible(true);
    }//GEN-LAST:event_btnNuevoServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevoServicio;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox cbAltaCIESP2;
    private javax.swing.JComboBox cbEstados2;
    private javax.swing.JComboBox cbMunicipios2;
    private org.jdesktop.swingx.JXDatePicker dpInicioServicios2;
    private org.jdesktop.swingx.JXDatePicker dpVigenciaServicios2;
    private javax.swing.JLabel lblClienteNombreBusca;
    private javax.swing.JLabel lblCodPostal2;
    private javax.swing.JLabel lblColonia2;
    private javax.swing.JLabel lblComentarios2;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDiaPagos;
    private javax.swing.JLabel lblDomicilio2;
    private javax.swing.JLabel lblEncCorreo2;
    private javax.swing.JLabel lblEncTelCelular2;
    private javax.swing.JLabel lblEncTelOficina2;
    private javax.swing.JLabel lblEncargado2;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblExterior2;
    private javax.swing.JLabel lblFacturación;
    private javax.swing.JLabel lblGiroBusca;
    private javax.swing.JLabel lblHorario2;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblInterior2;
    private javax.swing.JLabel lblMunicipio2;
    private javax.swing.JLabel lblNombreComercialBusca;
    private javax.swing.JLabel lblPagos;
    private javax.swing.JLabel lblPagosCelular;
    private javax.swing.JLabel lblPagosTelOficina;
    private javax.swing.JLabel lblPesos1;
    private javax.swing.JLabel lblPesos2;
    private javax.swing.JLabel lblPesos3;
    private javax.swing.JLabel lblRFCBusca;
    private javax.swing.JLabel lblRazonSocialBusca;
    private javax.swing.JLabel lblRepCorreo2;
    private javax.swing.JLabel lblRepTelCelular2;
    private javax.swing.JLabel lblRepTelOficina2;
    private javax.swing.JLabel lblRepresentante2;
    private javax.swing.JLabel lblRevision;
    private javax.swing.JLabel lblServiciosInicio2;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTelefonos2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVigenciaContrato2;
    private javax.swing.JPanel pBuscaCliente;
    private javax.swing.JPanel pGeneralesBusca;
    private javax.swing.JPanel pPagos;
    private javax.swing.JPanel pServicios;
    private javax.swing.JPanel pTotalFacturacion;
    private javax.swing.JRadioButton rbEvento;
    private javax.swing.JRadioButton rbMensual;
    private javax.swing.JRadioButton rbQuincenal;
    private javax.swing.JScrollPane spBuscaCliente;
    private javax.swing.JScrollPane spServicios;
    private javax.swing.JTable tServicios;
    private javax.swing.JTabbedPane tpDatosClienteBusca;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodPostal2;
    private javax.swing.JTextField txtColonia2;
    private javax.swing.JTextField txtComentarios2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDiaPagos;
    private javax.swing.JTextField txtDomicilio2;
    private javax.swing.JTextField txtEncCorreo2;
    private javax.swing.JTextField txtEncTelCelular2;
    private javax.swing.JTextField txtEncTelOficina2;
    private javax.swing.JTextField txtEncargado2;
    private javax.swing.JTextField txtFacturaIVA;
    private javax.swing.JTextField txtFacturaSubtotal;
    private javax.swing.JTextField txtFacturaTotal;
    private javax.swing.JTextField txtGiroBusca;
    private javax.swing.JTextField txtHorario2;
    private javax.swing.JTextField txtNombreClienteBusca;
    private javax.swing.JTextField txtNombreComercialBusca;
    private javax.swing.JTextField txtNumeroExterior2;
    private javax.swing.JTextField txtNumeroInterior2;
    private javax.swing.JTextField txtPagos;
    private javax.swing.JTextField txtPagosTelOficina;
    private javax.swing.JTextField txtRFCBusca;
    private javax.swing.JTextField txtRazonSocialBusca;
    private javax.swing.JTextField txtRepCorreo2;
    private javax.swing.JTextField txtRepTelCelular2;
    private javax.swing.JTextField txtRepTelOficina2;
    private javax.swing.JTextField txtRepresentante2;
    private javax.swing.JTextField txtRevision;
    private javax.swing.JTextField txtTelefonos2;
    // End of variables declaration//GEN-END:variables
}
