/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.controldepersonal.interfaz;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.controldepersonal.conector.conector;

/**
 *
 * @author Miguel
 */
public class BusquedaElemento extends javax.swing.JDialog {

    /**
     * Creates new form BusquedaElemento
     */
    private int numeroElemento= 0;
    conector conexionactual;
    private String[] cursosArray = new String[100];
    private int contadorCursos = 0;
    private DefaultTableModel modeloCursos;
    private String[] empleoArray = new String[10];
    private int contadorEmpleos = 0;
    private DefaultTableModel modeloEmpleos;
    public BusquedaElemento(java.awt.Frame parent, boolean modal,conector conexionactual,int numeroElemento) {
        super(parent, modal);
        this.conexionactual = conexionactual;
        this.numeroElemento = numeroElemento;
        initComponents();
        setTitle("Busqueda de Personal");
        System.out.println(this.numeroElemento);
        busquedaElemento(this.numeroElemento);
    }
    
    private void busquedaElemento(int numero){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgCartillaMilitar = new javax.swing.ButtonGroup();
        bgHojaDatosEntrega = new javax.swing.ButtonGroup();
        bgSolicitudEntrega = new javax.swing.ButtonGroup();
        bgIfeEntrega = new javax.swing.ButtonGroup();
        bgActaNacimientoEntrega = new javax.swing.ButtonGroup();
        bgCurpRfcEntrega = new javax.swing.ButtonGroup();
        bgComprobanteDomicilioEntrega = new javax.swing.ButtonGroup();
        bgCartaNoAntecedentesEntrega = new javax.swing.ButtonGroup();
        bgComprobanteEstudiosEntrega = new javax.swing.ButtonGroup();
        bgCartillaMilitarEntrega = new javax.swing.ButtonGroup();
        bgNumeroImssEntrega = new javax.swing.ButtonGroup();
        bgCartaRecomendacionEntrega = new javax.swing.ButtonGroup();
        bgContratoEntrega = new javax.swing.ButtonGroup();
        bgSocioeconomicoEntrega = new javax.swing.ButtonGroup();
        bgFotoSocioeconomicoEntrega = new javax.swing.ButtonGroup();
        bgPsicologicoEntrega = new javax.swing.ButtonGroup();
        bgComprobanteMedicoEntrega = new javax.swing.ButtonGroup();
        bgToxicologicoEntrega = new javax.swing.ButtonGroup();
        bgResguardoEntrega = new javax.swing.ButtonGroup();
        bgMapaDomicilioEntrega = new javax.swing.ButtonGroup();
        bgSepRegistroEstudios = new javax.swing.ButtonGroup();
        bgSocio1 = new javax.swing.ButtonGroup();
        bgSocio1Casa = new javax.swing.ButtonGroup();
        bgSocio1CasaTipo = new javax.swing.ButtonGroup();
        bgCurso = new javax.swing.ButtonGroup();
        bgCursoStatus = new javax.swing.ButtonGroup();
        spElementoEncontrado = new javax.swing.JScrollPane();
        pElemento = new javax.swing.JPanel();
        tpElemento = new javax.swing.JTabbedPane();
        pDatosElemento = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblServicio = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        lblEmpresa = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblPuesto = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblAtencion = new javax.swing.JLabel();
        dpAtencion = new org.jdesktop.swingx.JXDatePicker();
        lblInicioLabores = new javax.swing.JLabel();
        dpInicioLabores = new org.jdesktop.swingx.JXDatePicker();
        pRegistroSecretarias = new javax.swing.JPanel();
        lblRegistroCESP = new javax.swing.JLabel();
        txtRegistroCESP = new javax.swing.JTextField();
        lblCESPFecha = new javax.swing.JLabel();
        dpCESP = new org.jdesktop.swingx.JXDatePicker();
        lblCESPOficio = new javax.swing.JLabel();
        txtCESPOficio = new javax.swing.JTextField();
        lblVerificacion = new javax.swing.JLabel();
        txtVerificacion = new javax.swing.JTextField();
        lblVerificacionFecha = new javax.swing.JLabel();
        dpVerificacionFecha = new org.jdesktop.swingx.JXDatePicker();
        lblSSPF = new javax.swing.JLabel();
        txtSSPF = new javax.swing.JTextField();
        lblSSPFFecha = new javax.swing.JLabel();
        dpSSPFFecha = new org.jdesktop.swingx.JXDatePicker();
        lblRegistroSDN = new javax.swing.JLabel();
        txtSDNRegistro = new javax.swing.JTextField();
        lblSSPFOficio = new javax.swing.JLabel();
        txtSSPFOficio = new javax.swing.JTextField();
        lblSDNFecha = new javax.swing.JLabel();
        dpSDNFecha = new org.jdesktop.swingx.JXDatePicker();
        lblSDNOficio = new javax.swing.JLabel();
        txtSDNOficio = new javax.swing.JTextField();
        lblSDN = new javax.swing.JLabel();
        txtSDN = new javax.swing.JTextField();
        pFotos = new javax.swing.JPanel();
        pFotoFrente = new javax.swing.JPanel();
        pFotoDerecha = new javax.swing.JPanel();
        pFotoIzquierda = new javax.swing.JPanel();
        btnIzq = new javax.swing.JButton();
        btnDer = new javax.swing.JButton();
        btnFrente = new javax.swing.JButton();
        btnDetalles = new javax.swing.JButton();
        pDocumentos = new javax.swing.JPanel();
        lblDocumentos = new javax.swing.JLabel();
        cbDocumentos = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pElemento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setText("Nombre:");

        lblServicio.setText("Servicio:");

        lblEmpresa.setText("Empresa:");

        lblNumero.setText("Número:");

        lblPuesto.setText("Puesto:");

        lblStatus.setText("Status:");

        lblCiudad.setText("Ciudad:");

        lblEstado.setText("Estado:");

        lblAtencion.setText("Atención RH:");

        lblInicioLabores.setText("Inicio de labores:");

        pRegistroSecretarias.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro ante Secretarías"));

        lblRegistroCESP.setText("Registro CESP:");

        txtRegistroCESP.setText("ACEPTADO NO");

        lblCESPFecha.setText("Fecha:");

        lblCESPOficio.setText("Oficio:");

        lblVerificacion.setText("Verificación:");

        lblVerificacionFecha.setText("Fecha:");

        lblSSPF.setText("Registro SSPF:");

        lblSSPFFecha.setText("Fecha:");

        lblRegistroSDN.setText("Registro SDN:");

        lblSSPFOficio.setText("Oficio:");

        lblSDNFecha.setText("Fecha:");

        lblSDNOficio.setText("Oficio:");

        lblSDN.setText("Lic Part Col:");

        javax.swing.GroupLayout pRegistroSecretariasLayout = new javax.swing.GroupLayout(pRegistroSecretarias);
        pRegistroSecretarias.setLayout(pRegistroSecretariasLayout);
        pRegistroSecretariasLayout.setHorizontalGroup(
            pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistroSecretariasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRegistroSecretariasLayout.createSequentialGroup()
                        .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegistroCESP)
                            .addComponent(lblVerificacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVerificacion)
                            .addComponent(txtRegistroCESP, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(pRegistroSecretariasLayout.createSequentialGroup()
                        .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSSPF)
                            .addComponent(lblRegistroSDN)
                            .addComponent(lblSDN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSSPF)
                            .addComponent(txtSDNRegistro)
                            .addComponent(txtSDN, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pRegistroSecretariasLayout.createSequentialGroup()
                        .addComponent(lblCESPFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpCESP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCESPOficio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCESPOficio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pRegistroSecretariasLayout.createSequentialGroup()
                        .addComponent(lblVerificacionFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpVerificacionFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pRegistroSecretariasLayout.createSequentialGroup()
                        .addComponent(lblSSPFFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpSSPFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSSPFOficio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSSPFOficio))
                    .addGroup(pRegistroSecretariasLayout.createSequentialGroup()
                        .addComponent(lblSDNFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpSDNFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSDNOficio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDNOficio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pRegistroSecretariasLayout.setVerticalGroup(
            pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegistroSecretariasLayout.createSequentialGroup()
                .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistroCESP)
                    .addComponent(txtRegistroCESP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCESPFecha)
                    .addComponent(dpCESP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCESPOficio)
                    .addComponent(txtCESPOficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerificacion)
                    .addComponent(txtVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerificacionFecha)
                    .addComponent(dpVerificacionFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSPF)
                    .addComponent(txtSSPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSPFFecha)
                    .addComponent(dpSSPFFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSPFOficio)
                    .addComponent(txtSSPFOficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistroSDN)
                    .addComponent(txtSDNRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSDNFecha)
                    .addComponent(dpSDNFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSDNOficio)
                    .addComponent(txtSDNOficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRegistroSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSDN)
                    .addComponent(txtSDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pFotos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pFotos.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pFotoFrenteLayout = new javax.swing.GroupLayout(pFotoFrente);
        pFotoFrente.setLayout(pFotoFrenteLayout);
        pFotoFrenteLayout.setHorizontalGroup(
            pFotoFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );
        pFotoFrenteLayout.setVerticalGroup(
            pFotoFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        pFotos.add(pFotoFrente, "pFotoFrente");

        javax.swing.GroupLayout pFotoDerechaLayout = new javax.swing.GroupLayout(pFotoDerecha);
        pFotoDerecha.setLayout(pFotoDerechaLayout);
        pFotoDerechaLayout.setHorizontalGroup(
            pFotoDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );
        pFotoDerechaLayout.setVerticalGroup(
            pFotoDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        pFotos.add(pFotoDerecha, "pFotoDerecha");

        javax.swing.GroupLayout pFotoIzquierdaLayout = new javax.swing.GroupLayout(pFotoIzquierda);
        pFotoIzquierda.setLayout(pFotoIzquierdaLayout);
        pFotoIzquierdaLayout.setHorizontalGroup(
            pFotoIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );
        pFotoIzquierdaLayout.setVerticalGroup(
            pFotoIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        pFotos.add(pFotoIzquierda, "pFotoIzquierda");

        btnIzq.setText("Izq");

        btnDer.setText("Der");

        btnFrente.setText("F");

        btnDetalles.setText("Detalles");
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDatosElementoLayout = new javax.swing.GroupLayout(pDatosElemento);
        pDatosElemento.setLayout(pDatosElementoLayout);
        pDatosElementoLayout.setHorizontalGroup(
            pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosElementoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAtencion)
                    .addGroup(pDatosElementoLayout.createSequentialGroup()
                        .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblServicio)
                            .addComponent(lblEmpresa)
                            .addComponent(lblPuesto)
                            .addComponent(lblEstado))
                        .addGap(39, 39, 39)
                        .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDatosElementoLayout.createSequentialGroup()
                                .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtServicio)
                                    .addComponent(txtEmpresa)
                                    .addComponent(txtPuesto)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCiudad)
                                    .addComponent(lblNumero)
                                    .addComponent(lblStatus))
                                .addGap(18, 18, 18)
                                .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pDatosElementoLayout.createSequentialGroup()
                                .addComponent(dpAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblInicioLabores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dpInicioLabores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(btnDetalles)
                                .addGap(24, 24, 24))))
                    .addComponent(pRegistroSecretarias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pFotos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pDatosElementoLayout.createSequentialGroup()
                        .addComponent(btnIzq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFrente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDer)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        pDatosElementoLayout.setVerticalGroup(
            pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosElementoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDatosElementoLayout.createSequentialGroup()
                        .addComponent(pFotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIzq)
                            .addComponent(btnDer)
                            .addComponent(btnFrente)))
                    .addGroup(pDatosElementoLayout.createSequentialGroup()
                        .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpresa)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblServicio)
                            .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCiudad)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuesto)
                            .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(pDatosElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAtencion)
                            .addComponent(dpAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInicioLabores)
                            .addComponent(dpInicioLabores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDetalles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pRegistroSecretarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        tpElemento.addTab("Datos", pDatosElemento);

        pElemento.add(tpElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 460));

        lblDocumentos.setText("Generar documentación:");

        javax.swing.GroupLayout pDocumentosLayout = new javax.swing.GroupLayout(pDocumentos);
        pDocumentos.setLayout(pDocumentosLayout);
        pDocumentosLayout.setHorizontalGroup(
            pDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDocumentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDocumentos, 0, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        pDocumentosLayout.setVerticalGroup(
            pDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDocumentosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumentos)
                    .addComponent(cbDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pElemento.add(pDocumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 400, 80));

        spElementoEncontrado.setViewportView(pElemento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spElementoEncontrado, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spElementoEncontrado, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        DetallesElemento detallesElemento = new DetallesElemento(new javax.swing.JFrame(), false, conexionactual);
        detallesElemento.setVisible(true);
    }//GEN-LAST:event_btnDetallesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgActaNacimientoEntrega;
    private javax.swing.ButtonGroup bgCartaNoAntecedentesEntrega;
    private javax.swing.ButtonGroup bgCartaRecomendacionEntrega;
    private javax.swing.ButtonGroup bgCartillaMilitar;
    private javax.swing.ButtonGroup bgCartillaMilitarEntrega;
    private javax.swing.ButtonGroup bgComprobanteDomicilioEntrega;
    private javax.swing.ButtonGroup bgComprobanteEstudiosEntrega;
    private javax.swing.ButtonGroup bgComprobanteMedicoEntrega;
    private javax.swing.ButtonGroup bgContratoEntrega;
    private javax.swing.ButtonGroup bgCurpRfcEntrega;
    private javax.swing.ButtonGroup bgCurso;
    private javax.swing.ButtonGroup bgCursoStatus;
    private javax.swing.ButtonGroup bgFotoSocioeconomicoEntrega;
    private javax.swing.ButtonGroup bgHojaDatosEntrega;
    private javax.swing.ButtonGroup bgIfeEntrega;
    private javax.swing.ButtonGroup bgMapaDomicilioEntrega;
    private javax.swing.ButtonGroup bgNumeroImssEntrega;
    private javax.swing.ButtonGroup bgPsicologicoEntrega;
    private javax.swing.ButtonGroup bgResguardoEntrega;
    private javax.swing.ButtonGroup bgSepRegistroEstudios;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.ButtonGroup bgSocio1;
    private javax.swing.ButtonGroup bgSocio1Casa;
    private javax.swing.ButtonGroup bgSocio1CasaTipo;
    private javax.swing.ButtonGroup bgSocioeconomicoEntrega;
    private javax.swing.ButtonGroup bgSolicitudEntrega;
    private javax.swing.ButtonGroup bgToxicologicoEntrega;
    private javax.swing.JButton btnDer;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnFrente;
    private javax.swing.JButton btnIzq;
    private javax.swing.JComboBox cbDocumentos;
    private org.jdesktop.swingx.JXDatePicker dpAtencion;
    private org.jdesktop.swingx.JXDatePicker dpCESP;
    private org.jdesktop.swingx.JXDatePicker dpInicioLabores;
    private org.jdesktop.swingx.JXDatePicker dpSDNFecha;
    private org.jdesktop.swingx.JXDatePicker dpSSPFFecha;
    private org.jdesktop.swingx.JXDatePicker dpVerificacionFecha;
    private javax.swing.JLabel lblAtencion;
    private javax.swing.JLabel lblCESPFecha;
    private javax.swing.JLabel lblCESPOficio;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDocumentos;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblInicioLabores;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblRegistroCESP;
    private javax.swing.JLabel lblRegistroSDN;
    private javax.swing.JLabel lblSDN;
    private javax.swing.JLabel lblSDNFecha;
    private javax.swing.JLabel lblSDNOficio;
    private javax.swing.JLabel lblSSPF;
    private javax.swing.JLabel lblSSPFFecha;
    private javax.swing.JLabel lblSSPFOficio;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblVerificacion;
    private javax.swing.JLabel lblVerificacionFecha;
    private javax.swing.JPanel pDatosElemento;
    private javax.swing.JPanel pDocumentos;
    private javax.swing.JPanel pElemento;
    private javax.swing.JPanel pFotoDerecha;
    private javax.swing.JPanel pFotoFrente;
    private javax.swing.JPanel pFotoIzquierda;
    private javax.swing.JPanel pFotos;
    private javax.swing.JPanel pRegistroSecretarias;
    private javax.swing.JScrollPane spElementoEncontrado;
    private javax.swing.JTabbedPane tpElemento;
    private javax.swing.JTextField txtCESPOficio;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtRegistroCESP;
    private javax.swing.JTextField txtSDN;
    private javax.swing.JTextField txtSDNOficio;
    private javax.swing.JTextField txtSDNRegistro;
    private javax.swing.JTextField txtSSPF;
    private javax.swing.JTextField txtSSPFOficio;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtVerificacion;
    // End of variables declaration//GEN-END:variables

}
