/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.controldepersonal.interfaz;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import org.controldepersonal.conector.conector;
import org.controldepersonal.controlerrores.administradorDeFallos;
/* *********************** */
/**
 *
 * @author Miguel
 */
public class framePrincipal extends javax.swing.JFrame {
    conector conexionactual;
    administradorDeFallos administradorErrores;
    /**
     * Creates new form framePrincipal
     * @param conexionactual
     */
    public framePrincipal(conector conexionactual, administradorDeFallos administradorErrores) {
        initComponents();
        //Iniciar maximizado
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //continuamos con la conexion provicionado por el login
        this.conexionactual = conexionactual;
        this.administradorErrores = administradorErrores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        btnElemento = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnAsistencia = new javax.swing.JButton();
        btnEquipo = new javax.swing.JButton();
        panelOpciones = new javax.swing.JPanel();
        panelElemento = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        panelDoc = new javax.swing.JPanel();
        panelServicios = new javax.swing.JPanel();
        panelAsistencia = new javax.swing.JPanel();
        panelEquipo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnElemento.setText("Elemento");
        btnElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElementoActionPerformed(evt);
            }
        });

        btnDoc.setText("Doc general");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        btnServicios.setText("Clientes/Servicios");
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });

        btnAsistencia.setText("Asistencia");
        btnAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaActionPerformed(evt);
            }
        });

        btnEquipo.setText("Equipo");
        btnEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnServicios)
                    .addComponent(btnDoc)
                    .addComponent(btnElemento)
                    .addComponent(btnAsistencia)
                    .addComponent(btnEquipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnElemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnDoc)
                .addGap(30, 30, 30)
                .addComponent(btnServicios)
                .addGap(36, 36, 36)
                .addComponent(btnAsistencia)
                .addGap(28, 28, 28)
                .addComponent(btnEquipo)
                .addGap(36, 36, 36))
        );

        panelOpciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelOpciones.setLayout(new java.awt.CardLayout());

        panelElemento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setText("Registrar Elemento");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        panelElemento.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, 57));

        btnBuscar.setText("Buscar Elemento");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelElemento.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 205, 180, 60));

        panelOpciones.add(panelElemento, "panelElemento");

        javax.swing.GroupLayout panelDocLayout = new javax.swing.GroupLayout(panelDoc);
        panelDoc.setLayout(panelDocLayout);
        panelDocLayout.setHorizontalGroup(
            panelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        panelDocLayout.setVerticalGroup(
            panelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        panelOpciones.add(panelDoc, "panelDoc");

        javax.swing.GroupLayout panelServiciosLayout = new javax.swing.GroupLayout(panelServicios);
        panelServicios.setLayout(panelServiciosLayout);
        panelServiciosLayout.setHorizontalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        panelServiciosLayout.setVerticalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        panelOpciones.add(panelServicios, "panelServicios");

        javax.swing.GroupLayout panelAsistenciaLayout = new javax.swing.GroupLayout(panelAsistencia);
        panelAsistencia.setLayout(panelAsistenciaLayout);
        panelAsistenciaLayout.setHorizontalGroup(
            panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        panelAsistenciaLayout.setVerticalGroup(
            panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        panelOpciones.add(panelAsistencia, "panelAsistencias");

        javax.swing.GroupLayout panelEquipoLayout = new javax.swing.GroupLayout(panelEquipo);
        panelEquipo.setLayout(panelEquipoLayout);
        panelEquipoLayout.setHorizontalGroup(
            panelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        panelEquipoLayout.setVerticalGroup(
            panelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        panelOpciones.add(panelEquipo, "panelEquipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElementoActionPerformed
        CardLayout card = (CardLayout) panelOpciones.getLayout();
        card.show(panelOpciones, "panelElemento");
    }//GEN-LAST:event_btnElementoActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        CardLayout card = (CardLayout) panelOpciones.getLayout();
        card.show(panelOpciones, "panelDoc");
    }//GEN-LAST:event_btnDocActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        CardLayout card = (CardLayout) panelOpciones.getLayout();
        card.show(panelOpciones, "panelServicios");
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
        CardLayout card = (CardLayout) panelOpciones.getLayout();
        card.show(panelOpciones, "panelAsistencia");
    }//GEN-LAST:event_btnAsistenciaActionPerformed

    private void btnEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipoActionPerformed
        CardLayout card = (CardLayout) panelOpciones.getLayout();
        card.show(panelOpciones, "panelEquipo");
    }//GEN-LAST:event_btnEquipoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        RegistrarElemento registrarElemento = new RegistrarElemento(new javax.swing.JFrame(), false, conexionactual);
        registrarElemento.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        SeleccionarBusquedaElemento buscarElemento = new SeleccionarBusquedaElemento(new javax.swing.JFrame(),false,conexionactual);
        buscarElemento.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnElemento;
    private javax.swing.JButton btnEquipo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnServicios;
    private javax.swing.JPanel panelAsistencia;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDoc;
    private javax.swing.JPanel panelElemento;
    private javax.swing.JPanel panelEquipo;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelServicios;
    // End of variables declaration//GEN-END:variables
}

