/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.controldepersonal.interfazAsistencia;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import org.controldepersonal.conector.conector;

/**
 *
 * @author Miguel
 */
public class AsistenciaJustificada extends javax.swing.JDialog {

    /**
     * Creates new form AsistenciaJustificada
     */
    conector conexionactual;
    private int id_empleado;
    private String Justificada;
    public AsistenciaJustificada(java.awt.Frame parent, boolean modal,conector conexionactual,int id_empleado,String Justificada) {
        super(parent, modal);
        this.conexionactual = conexionactual;
        this.id_empleado = id_empleado;
        this.Justificada = Justificada;
        initComponents();
        setTitle("Selecciona la fecha a justificar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAsistenciaJustificada = new javax.swing.JLabel();
        dpAsistenciaJustificada = new org.jdesktop.swingx.JXDatePicker();
        btnJustificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAsistenciaJustificada.setText("Selecciona el día:");

        btnJustificar.setText("Justificar");
        btnJustificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJustificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAsistenciaJustificada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpAsistenciaJustificada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJustificar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsistenciaJustificada)
                    .addComponent(dpAsistenciaJustificada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJustificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJustificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJustificarActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = dateFormat.format(dpAsistenciaJustificada.getDate());
        fecha = arreglaFecha(fecha);
        if(conexionactual.justificaAsistencia(id_empleado, fecha, Justificada)){            
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "No hay falta registrada");
            this.dispose();
        }
    }//GEN-LAST:event_btnJustificarActionPerformed
    private String arreglaFecha(String fecha){
        String[] temp = fecha.split("/");
        switch(temp[1]){
            case "01":
                temp[1] = "1";
            break;
            case "02":
                temp[1] = "2";
            break;
            case "03":
                temp[1] = "3";
            break;
            case "04":
                temp[1] = "4";
            break;
            case "05":
                temp[1] = "5";
            break;
            case "06":
                temp[1] = "6";
            break;
            case "07":
                temp[1] = "7";
            break;
            case "08":
                temp[1] = "8";
            break;
            case "09":
                temp[1] = "9";
            break;
            case "10":
                temp[1] = "10";
            break;
            case "11":
                temp[1] = "11";
            break;
            case "12":
                temp[1] = "12";
            break;
        }
        return temp[0]+"/"+temp[1]+"/"+temp[2];
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJustificar;
    private org.jdesktop.swingx.JXDatePicker dpAsistenciaJustificada;
    private javax.swing.JLabel lblAsistenciaJustificada;
    // End of variables declaration//GEN-END:variables
}
